name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd cmd-searcher
          npm ci

      - name: Build Next.js app
        run: |
          cd cmd-searcher
          npm run build
          
      - name: Prepare deployment directory
        run: |
          mkdir -p deploy
          cp -r README.md lib/ docs/ deploy/
          cp -r cmd-searcher/out/* deploy/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages